/**
 * =============================================================================
 * STATUS & VALIDATION UI MODULE (Status)
 * =============================================================================
 * Handles all the real-time DOM updates for the System Validation dashboard.
 * * WHY IT EXISTS: When the user clicks "Refresh", the backend takes a few 
 * seconds to scan the network and hard drive. This file manages the "Loading" 
 * animations, and then unpacks the giant payload from OsSvc to paint the UI.
 */

import { I18n } from '../core/i18n.js';

export const Status = {
    // =========================================================================
    // --- UI SPINNERS & LOADING STATES ---
    // =========================================================================

    /**
     * Toggles the loading animation on the Dashboard.
     * @param {boolean} isLoading - True to show spinners, false to restore normal UI.
     */
    setValidationLoading: (isLoading) => {
        // 1. Find the Refresh Button 
        // (Uses a fuzzy selector to find any button that starts with 'UI.runValidation')
        const btn = document.querySelector('[data-action="run-validation"]');

        if (btn) {
            btn.disabled = isLoading; // Prevent double-clicking
            
            // Swap the SVG icon with a Bootstrap spinner
            btn.innerHTML = isLoading 
                ? `<span class="spinner-border spinner-border-sm"></span> Scanning...`
                : `<svg width="18" height="18"><use href="#icon-refresh"></use></svg> <span>${__('validation.refresh')}</span>`;
            
            // 🚨 CRITICAL FIX: Because we just overwrote the button's innerHTML, 
            // the <span i18n="validation.refresh"> is completely raw and untranslated!
            // We must re-run the dictionary apply function to translate it back.
            if (!isLoading) I18n.apply();
        }

        // 2. Grey out all data fields while we wait
        if (isLoading) {
            const loadingHtml = '<span class="text-muted small">Fetching...</span>';
            
            ['sys-hostname', 'sys-ip', 'sys-os', 'sys-ram', 'sys-cpu', 'sys-drive-d'].forEach(id => {
                const el = document.getElementById(id);
                if (el) el.innerHTML = loadingHtml;
            });

            // 3. Reset all Network/App Badges to neutral grey
            document.querySelectorAll('#server-validation-view .badge').forEach(b => {
                b.className = 'badge bg-secondary px-2 py-1';
                b.innerText = '...';
            });
        }
    },

    // =========================================================================
    // --- PAYLOAD UNPACKING & PAINTING ---
    // =========================================================================

    /**
     * Takes the massive JSON payload generated by OsSvc (via API.getSystemInfo) 
     * and maps the data to specific HTML IDs on the dashboard.
     * @param {Object} info - The aggregated system data.
     */
    updateValidationBadges: (info) => {
        // --- HELPER 1: Text Inserter ---
        const setVal = (id, val) => {
            const el = document.getElementById(id);
            if (el) el.innerText = val || 'Unknown';
        };

        // 1. Paint Hardware Data
        setVal('sys-hostname', info.hostname);
        setVal('sys-ip', info.ip);
        setVal('sys-os', info.osVersion);
        setVal('sys-ram', info.ramGB ? `${info.ramGB} GB` : null);
        setVal('sys-cpu', info.cpuInfo);

        // 2. Paint Storage Data (Dynamically builds HTML for C: and the Target Drive)
        const storageEl = document.getElementById('sys-drive-d');
        if (info.storage && storageEl) {
            let html = '';
            
            // Always show the C: Drive
            if (info.storage.c) {
                html += `<div class="mb-1 text-dark" style="font-size: 0.8rem;">
                            <span class="text-success">${info.storage.c.letter}</span> ${info.storage.c.free}GB free of ${info.storage.c.total}GB
                         </div>`;
            }
            
            // If the user selected 'D:\' or 'E:\' in settings, show that too!
            if (info.storage.target) {
                html += `<div class="text-dark" style="font-size: 0.8rem;">
                            <span class="text-success">${info.storage.target.letter}</span> ${info.storage.target.free}GB free of ${info.storage.target.total}GB
                         </div>`;
            }
            storageEl.innerHTML = html || 'Unknown';
        }

        // --- HELPER 2: Badge Painter ---
        // Converts a boolean (true/false) into a Green or Red bootstrap pill.
        const setBadge = (id, isSuccess, successText = "Installed", failText = "Not Found") => {
            const el = document.getElementById(id);
            if (!el) return;
            el.innerText = isSuccess ? successText : failText;
            el.className = isSuccess ? "badge bg-success px-2 py-1" : "badge bg-danger px-2 py-1";
        };

        // 3. Paint Network Firewalls
        // Uses the 'w' (Whitelisted) and 'b' (Blocked) overrides instead of Installed/Not Found.
        const w = "Whitelisted", b = "Blocked";
        setBadge('status-upload', info.urls.upload, w, b);
        setBadge('status-deploy', info.urls.deploy, w, b);
        setBadge('status-google', info.urls.google, w, b);
        setBadge('status-innovar', info.urls.innovar, w, b);
        setBadge('status-nextgen', info.urls.nextgen, w, b);

        // 4. Paint App Installations
        setBadge('status-tmsdos', info.apps.tmsDos);
        setBadge('status-mirth', info.apps.mirth);
        setBadge('status-bridgelink', info.apps.bridgelink);
        setBadge('status-vscode', info.apps.vscode);
        setBadge('status-heidi', info.apps.heidiSQL);
    }
};